metodos-numericos/app/__init__.py
from flask import Flask

def create_app():
    app = Flask(__name__)

    # Configuraciones
    app.config['SECRET_KEY'] = 'mysecretkey'

    # Importa rutas y registra blueprints
    from .routes import main_routes
    app.register_blueprint(main_routes)

    return app

metodos-numericos/app/routes.py
from flask import Blueprint, render_template, redirect, url_for
from flask import request
from app.functions.solve import solve_non_linear_equation, solve_derivatives, solve_dif_number

main_routes = Blueprint('main_routes', __name__)

@main_routes.route('/')
def index():
    return redirect(url_for('main_routes.home'))

@main_routes.route('/home')
def home():
    return render_template('home.html')

@main_routes.route('/nonlinear_equation')
def nonlinear_equation():
    return render_template('nonlinear_equation.html')

@main_routes.route('/about')
def about():
    return render_template('about.html')

@main_routes.route('/nonlinear_equation', methods=['POST'])
def nonlinear_equations():
    result = solve_non_linear_equation(request.form)
    return render_template('nonlinear_equation.html', result=result)

@main_routes.route('/derivatives')
def derivatives():
    return render_template('derivatives.html')

@main_routes.route('/derivatives-two-points', methods=['POST'])
def derivatives_two_points():
    result = solve_derivatives(request.form)
    return render_template('derivatives.html', result=result)

@main_routes.route('/dif_number')
def dif_number():
    return render_template('dif_number.html')

@main_routes.route('/dif_number', methods=['POST'])
def dif_numbers():
    result = solve_dif_number(request.form)
    return render_template('dif_number.html', result=result)

metodos-numericos/app/templates/about.html
{% extends 'layout.html' %}

{% block content %}
    <h1>About Us</h1>
    <p>This is the about page.</p>
{% endblock %}

metodos-numericos/app/templates/derivatives.html
{% extends 'layout.html' %}

{% block content %}
    <section class="border rounded-md border-gray-200 p-5 dark:border-gray-800 text-gray-600 dark:text-gray-100 text-sm">
        <h2 class="text-lg font-semibold uppercase">Solución Numérica de Derivadas</h2>
        <form method="POST" id="derivatives_form" action="{{ url_for('main_routes.derivatives_two_points') }}">
            <div class="grid grid-cols-[3fr_repeat(5,_1fr)] gap-2 w-full mt-3 mb-1">
                <select name="method" id="method" class="py-1 px-2 shadow border border-gray-200 dark:border-gray-800 rounded-md focus:outline-none dark:bg-transparent dark:border-gray-800 text-gray-700 dark:text-gray-400">
                    <option selected value="0">Selecione el método a usar...</option>
                    <option value="1">Dos puntos</option>
                    <option value="2">Tres puntos hacia adelante</option>
                    <option value="3">Tres puntos hacia atras</option>
                    <option value="4">Tres puntos</option>
                  </select>
                <input type="text" name="equation" id="equation" placeholder="Ingrese la ecuación" class="inline-block py-1 px-2 items-center shadow border border-gray-200 dark:border-gray-800 rounded-md focus:outline-none dark:bg-black dark:border-gray-800 text-gray-700 dark:text-gray-400 hidden">
                <input type="text" name="x" id="x" placeholder="Ingrese x:" class="inline-block py-1 px-2 shadow border border-gray-200 dark:border-gray-800 rounded-md focus:outline-none dark:bg-black dark:border-gray-800 text-gray-700 dark:text-gray-400 hidden">
                <input type="text" name="tol" id="tol" placeholder="Ingrese TOL:" class="inline-block py-1 px-2 shadow border border-gray-200 dark:border-gray-800 rounded-md focus:outline-none dark:bg-black dark:border-gray-800 text-gray-700 dark:text-gray-400 hidden">
                <button id="buttonSend" class="inline-flex text-center items-center justify-center py-1 rounded-md shadow text-gray-700 dark:text-gray-400 dark:border-gray-800 border border-gray-200 leading-none hidden">Calcular</button>
            </div>
        </form>
        <div class="grid grid-cols-[3fr_repeat(5,_1fr)] gap-2 w-full mt-3 mb-1">
            <div></div>
            <div><small id="funcInfo" class="text-gray-400 dark:text-gray-600 hidden">Ex: 2 * X ** 3</small></div>
            <div><small id="xInfo" class="text-gray-400 dark:text-gray-600 hidden">Ex: 0.5</small></div>
            <div><small id="tolInfo" class="text-gray-400 dark:text-gray-600 hidden">Ex: 1e-6</small></div>
        </div>
    </section>
    <section class="border rounded-md border-gray-200 p-5 dark:border-gray-800 text-gray-600 dark:text-gray-100 text-sm mt-3 grid gap-2 grid-cols-[0.5fr_1fr]">
        <div class="bg-stone-950 p-3">
            <h4 class="text-sm font-semibold uppercase text-center mb-2">Solución</h4>
            {% if result %}
                <div>Función: {{ result.func_str[0] if result.func_str else None }}</div>
                <p>Resultado: {{ result.x[0] if result.x else None }}</p>
                </br>
                <p>Nro repeticiones: {{ result.iter_count[0] if result.iter_count else None }}</p>
            {% endif %}
        </div>
        <div class="border rounded border-gray-200 dark:border-gray-800 p-3">
            <h4 class="text-sm font-semibold uppercase text-center mb-2">Gráfica</h4>
            {% if result %}
            <img src="data:image/png;base64,{{ result.plot_data }}" alt="Graph of function" class="text-center mx-auto">
            {% endif %}
        </div>
    </section>

    <script>
        let equation = document.getElementById('equation')
        let xInput = document.getElementById('x');
        let tolInput = document.getElementById('tol');
        let buttonSend = document.getElementById('buttonSend')
        let textInfo = document.getElementById('funcInfo')
        let xInfo = document.getElementById('xInfo')
        let tolInfo = document.getElementById('tolInfo')

        document.getElementById('method').addEventListener('change', function () {
            let selectedMethod = this.value;
            if (selectedMethod != undefined || selectedMethod != null ) buttonSend.classList.remove('hidden')
            equation.classList.remove('hidden');
            xInput.classList.remove('hidden');
            tolInput.classList.remove('hidden');
            textInfo.classList.remove('hidden');
            xInfo.classList.remove('hidden');
            tolInfo.classList.remove('hidden');
        });

        document.getElementById('derivatives_form').addEventListener('submit', function(event) {
            validateForm(this);
        });
    </script>
{% endblock %}

metodos-numericos/app/templates/dif_number.html
{% extends 'layout.html' %}

{% block content %}
    <section class="border rounded-md border-gray-200 p-5 dark:border-gray-800 text-gray-600 dark:text-gray-100 text-sm">
        <h2 class="text-lg font-semibold uppercase">Diferenciación Numerica</h2>
        <form method="POST" id="dif_number_form" action="{{ url_for('main_routes.dif_number') }}">
            <div class="grid grid-cols-[3fr_repeat(5,_1fr)] gap-2 w-full mt-3 mb-1">
                <input type="text" name="equation" id="equation" placeholder="Ingrese la ecuación" class="inline-block py-1 px-2 items-center shadow border border-gray-200 dark:border-gray-800 rounded-md focus:outline-none dark:bg-black dark:border-gray-800 text-gray-700 dark:text-gray-400 hidden">
                <input type="text" name="a" id="a" placeholder="Ingrese A:" class="inline-block py-1 px-2 shadow border border-gray-200 dark:border-gray-800 rounded-md focus:outline-none dark:bg-black dark:border-gray-800 text-gray-700 dark:text-gray-400 hidden">
                <input type="text" name="b" id="b" placeholder="Ingrese B:" class="inline-block py-1 px-2 shadow border border-gray-200 dark:border-gray-800 rounded-md focus:outline-none dark:bg-black dark:border-gray-800 text-gray-700 dark:text-gray-400 hidden">
                <input type="number" name="n" id="n" placeholder="Ingrese N:" class="inline-block py-1 px-2 shadow border border-gray-200 dark:border-gray-800 rounded-md focus:outline-none dark:bg-black dark:border-gray-800 text-gray-700 dark:text-gray-400 hidden">
                <select name="method" id="method" class="py-1 px-2 shadow border border-gray-200 dark:border-gray-800 rounded-md focus:outline-none dark:bg-transparent dark:border-gray-800 text-gray-700 dark:text-gray-400">
                    <option selected value="0">Selecione el método a usar...</option>
                    <option value="1">Integración</option>
                    <option value="2">Regla de simpson</option>
                    <option value="3">Simpson 3-8</option>
                  </select>
                <button id="buttonSend" class="inline-flex text-center items-center justify-center py-1 rounded-md shadow text-gray-700 dark:text-gray-400 dark:border-gray-800 border border-gray-200 leading-none hidden">Calcular</button>
            </div>
        </form>
        <small id="textInfo" class="text-gray-400 dark:text-gray-600 hidden">Ex: x ** 3 - 2 * x ** 2 + 4 * x - 8 </small>
    </section>
    <section class="border rounded-md border-gray-200 p-5 dark:border-gray-800 text-gray-600 dark:text-gray-100 text-sm mt-3 grid gap-2 grid-cols-[0.5fr_1fr]">
        <div class="bg-stone-950 p-3">
            <h4 class="text-sm font-semibold uppercase text-center mb-2">Solución</h4>
            {% if result %}
            <p>Función: {{result.func_str[0] if result.func_str else None}}</p>
            <p>Aproximación de la raíz: {{result.x[0] if result.x else None}}</p>
            <p>Nro repeticiones: {{result.iter_count[0] if result.iter_count else None}}</p>
            {% endif %}
        </div>
        <div class="border rounded border-gray-200 dark:border-gray-800 p-3">
            <h4 class="text-sm font-semibold uppercase text-center mb-2">Gráfica</h4>
            {% if result %}
            <img src="data:image/png;base64,{{ result.plot_data }}" alt="Graph of function" class="text-center mx-auto">
            {% endif %}
        </div>
    </section>

    <script>
        let equation = document.getElementById('equation')
        let aInput = document.getElementById('a');
        let bInput = document.getElementById('b');
        let nInput = document.getElementById('n');
        let buttonSend = document.getElementById('buttonSend')
        let textInfo = document.getElementById('textInfo')

        document.getElementById('method').addEventListener('change', function () {
            let selectedMethod = this.value;

            if (selectedMethod != undefined || selectedMethod != null ) buttonSend.classList.remove('hidden')
            
            equation.classList.remove('hidden');
            aInput.classList.remove('hidden');
            bInput.classList.remove('hidden');
            nInput.classList.remove('hidden');
            textInfo.classList.remove('hidden');
        });

        document.getElementById('dif_number_form').addEventListener('submit', function(event) {
            validateForm(this);
        });
    </script>
{% endblock %}

metodos-numericos/app/templates/home.html
{% extends 'layout.html' %}

{% block content %}

<div class="w-full h-screen flex items-center justify-center">
    <div class="dark:bg-stone-950 dark:border-stone-950 rounded-lg shadow-lg p-8 space-y-4">
        <h1 class="text-3xl text-white font-bold text-center">¿Que desea calcular?</h1>
        <div class="flex justify-center space-x-4">
            <a href="{{ url_for('main_routes.nonlinear_equation') }}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                Ecuaciones lineales
            </a>
            <a href="{{ url_for('main_routes.derivatives') }}" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">
                Derivadas
            </a>
        </div>
    </div>
</div>

{% endblock %}

metodos-numericos/app/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <title>Métodos Numericos</title>
    <link rel="icon" href="{{ url_for('static', filename='img/think.ico') }}" type="image/x-icon">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <script type="text/javascript" async
      src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML">
    </script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css') }}">
</head>
<body>
    {% include 'nav.html' %}

    <main class="px-5 py-3">
        {% block content %}{% endblock %}

        <div id="alert" class="bg-slate-800 bg-opacity-50 flex justify-center items-center absolute top-0 right-0 bottom-0 left-0 hidden">
            <div class="dark:bg-stone-950 dark:border-stone-950 px-16 py-14 rounded-md text-center">
              <h1 id="alertText" class="text-xl mb-4 font-bold text-white">Do you Want Delete</h1>
              <button id="buttonClose" class="px-7 py-2 ml-2 inline-flex text-center items-center justify-center rounded-md shadow text-gray-700 dark:text-gray-400 dark:border-gray-800 border border-gray-200 leading-none"  onclick="closeAlert()">Aceptar</button>
            </div>
          </div>
    </main>

    <script>
        function showAlert(message) {
            document.getElementById('alertText').innerHTML = message;
            document.getElementById('alert').classList.remove('hidden');
        }
        
        function closeAlert() {
            document.getElementById('alertText').textContent = '';
            document.getElementById('alert').classList.add('hidden');
        }
        
        function validateForm(form) {
            event.preventDefault();
            var fields = form.getElementsByTagName('input');
            for (var i = 0; i < fields.length; i++) {
                var field = fields[i];
                if (field.value === '') {
                    showAlert(`Por favor, complete el campo <strong>${field.name}</strong> antes de enviar el formulario.`);
                return;
            }
        }
            form.submit();
        }
    </script>
</body>
</html>

metodos-numericos/app/templates/nav.html
<!-- component -->
<aside class="flex">
    <div class="flex flex-col items-center w-16 h-screen py-8 space-y-8 bg-white dark:bg-stone-950 dark:border-stone-950">
        <a href="{{ url_for('main_routes.home') }}">
            <img class="w-auto h-6" src="{{ url_for('static', filename='img/think.png') }}" alt="logo">
        </a>

        <a href="{{ url_for('main_routes.nonlinear_equation') }}" class="{% if url_for('main_routes.nonlinear_equation') == request.path %}text-blue-500 bg-blue-100 dark:text-blue-400 dark:bg-gray-800{% else %}text-gray-500 focus:outline-nones dark:text-gray-400 dark:hover:bg-gray-800 hover:bg-gray-100 {% endif %} p-1.5 transition-colors duration-200 rounded-lg">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
            </svg>
        </a>

        <a href="{{ url_for('main_routes.derivatives') }}" class="{% if 'derivatives' in request.path %}text-blue-500 bg-blue-100 dark:text-blue-400 dark:bg-gray-800{% else %}text-gray-500 focus:outline-nones dark:text-gray-400 dark:hover:bg-gray-800 hover:bg-gray-100 {% endif %} p-1.5 transition-colors duration-200 rounded-lg">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M15 19.128a9.38 9.38 0 002.625.372 9.337 9.337 0 004.121-.952 4.125 4.125 0 00-7.533-2.493M15 19.128v-.003c0-1.113-.285-2.16-.786-3.07M15 19.128v.106A12.318 12.318 0 018.624 21c-2.331 0-4.512-.645-6.374-1.766l-.001-.109a6.375 6.375 0 0111.964-3.07M12 6.375a3.375 3.375 0 11-6.75 0 3.375 3.375 0 016.75 0zm8.25 2.25a2.625 2.625 0 11-5.25 0 2.625 2.625 0 015.25 0z" />
            </svg>
        </a>

        <a href="{{ url_for('main_routes.dif_number') }}" class="{% if 'dif_number' in request.path %}text-blue-500 bg-blue-100 dark:text-blue-400 dark:bg-gray-800{% else %}text-gray-500 focus:outline-nones dark:text-gray-400 dark:hover:bg-gray-800 hover:bg-gray-100 {% endif %} p-1.5 transition-colors duration-200 rounded-lg">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M15 19.128a9.38 9.38 0 002.625.372 9.337 9.337 0 004.121-.952 4.125 4.125 0 00-7.533-2.493M15 19.128v-.003c0-1.113-.285-2.16-.786-3.07M15 19.128v.106A12.318 12.318 0 018.624 21c-2.331 0-4.512-.645-6.374-1.766l-.001-.109a6.375 6.375 0 0111.964-3.07M12 6.375a3.375 3.375 0 11-6.75 0 3.375 3.375 0 016.75 0zm8.25 2.25a2.625 2.625 0 11-5.25 0 2.625 2.625 0 015.25 0z" />
            </svg>
        </a>
    </div>
</aside>

metodos-numericos/app/templates/nonlinear_equation.html
{% extends 'layout.html' %}

{% block content %}
    <section class="border rounded-md border-gray-200 p-5 dark:border-gray-800 text-gray-600 dark:text-gray-100 text-sm">
        <h2 class="text-lg font-semibold uppercase">Solución Numérica de Ecuaciones No Lineales</h2>
        <form method="POST" id="non_linear_equations" action="{{ url_for('main_routes.nonlinear_equations') }}">
            <div class="grid grid-cols-[3fr_repeat(5,_1fr)] gap-2 w-full mt-3 mb-1">
                <input type="text" name="equation" id="equation" placeholder="Ingrese la ecuación" class="inline-block py-1 px-2 items-center shadow border border-gray-200 dark:border-gray-800 rounded-md focus:outline-none dark:bg-black dark:border-gray-800 text-gray-700 dark:text-gray-400 hidden">
                <input type="number" name="a" id="a" placeholder="Ingrese A:" class="inline-block py-1 px-2 shadow border border-gray-200 dark:border-gray-800 rounded-md focus:outline-none dark:bg-black dark:border-gray-800 text-gray-700 dark:text-gray-400 hidden">
                <input type="number" name="b" id="b" placeholder="Ingrese B:" class="inline-block py-1 px-2 shadow border border-gray-200 dark:border-gray-800 rounded-md focus:outline-none dark:bg-black dark:border-gray-800 text-gray-700 dark:text-gray-400 hidden">
                <input type="text" name="tol" id="tol" placeholder="Ingrese TOL:" class="inline-block py-1 px-2 shadow border border-gray-200 dark:border-gray-800 rounded-md focus:outline-none dark:bg-black dark:border-gray-800 text-gray-700 dark:text-gray-400 hidden">
                <select name="method" id="method" class="py-1 px-2 shadow border border-gray-200 dark:border-gray-800 rounded-md focus:outline-none dark:bg-transparent dark:border-gray-800 text-gray-700 dark:text-gray-400">
                    <option selected value="0">Selecione el método a usar...</option>
                    <option value="1">Bisección</option>
                    <option value="2">Regla falsa</option>
                  </select>
                <button id="buttonSend" class="inline-flex text-center items-center justify-center py-1 rounded-md shadow text-gray-700 dark:text-gray-400 dark:border-gray-800 border border-gray-200 leading-none hidden">Calcular</button>
            </div>
        </form>
        <small id="textInfo" class="text-gray-400 dark:text-gray-600 hidden">Ex: x ** 3 - 2 * x ** 2 + 4 * x - 8 </small>
    </section>
    <section class="border rounded-md border-gray-200 p-5 dark:border-gray-800 text-gray-600 dark:text-gray-100 text-sm mt-3 grid gap-2 grid-cols-[0.5fr_1fr]">
        <div class="bg-stone-950 p-3">
            <h4 class="text-sm font-semibold uppercase text-center mb-2">Solución</h4>
            {% if result %}
            <p>Función: {{result.func_str[0] if result.func_str else None}}</p>
            <p>Aproximación de la raíz: {{result.y_root[0] if result.y_root else None}}</p>
            <p>Nro repeticiones: {{result.iter_count[0] if result.iter_count else None}}</p>
            {% endif %}
        </div>
        <div class="border rounded border-gray-200 dark:border-gray-800 p-3">
            <h4 class="text-sm font-semibold uppercase text-center mb-2">Gráfica</h4>
            {% if result %}
            <img src="data:image/png;base64,{{ result.plot_data }}" alt="Graph of function" class="text-center mx-auto">
            {% endif %}
        </div>
    </section>

    <script>
        let equation = document.getElementById('equation')
        let aInput = document.getElementById('a');
        let bInput = document.getElementById('b');
        let tolInput = document.getElementById('tol');
        let buttonSend = document.getElementById('buttonSend')
        let textInfo = document.getElementById('textInfo')

        document.getElementById('method').addEventListener('change', function () {
            let selectedMethod = this.value;

            if (selectedMethod != undefined || selectedMethod != null ) buttonSend.classList.remove('hidden')
            
            equation.classList.remove('hidden');

            if (selectedMethod === '1' || selectedMethod === '2') {
                aInput.classList.remove('hidden');
                bInput.classList.remove('hidden');
                tolInput.classList.remove('hidden');
                textInfo.classList.remove('hidden');
            }else {
                equation.classList.add('hidden');
                buttonSend.classList.add("hidden")
                aInput.classList.add('hidden');
                bInput.classList.add('hidden');
                tolInput.classList.add('hidden');
                textInfo.classList.add('hidden');
            }
        });

        document.getElementById('non_linear_equations').addEventListener('submit', function(event) {
            validateForm(this);
        });
    </script>
{% endblock %}